requirejs.config({
  "baseUrl":"js",
  "paths":{
    //libs
    "Class":"libs/class",
    "Jquery":"libs/jquery",
    //classes
    "Animation":"app/classes/gfx/Animation",
    "Assets":"app/classes/gfx/Assets",
    "Creature":"app/classes/entities/creatures/Creature",
    "DirtTile":"app/classes/tiles/DirtTile",
    "Display":"app/classes/display/Display",
    "Entity":"app/classes/entities/Entity",
    "Game":"app/classes/Game",
    "GameCamera":"app/classes/gfx/GameCamera",
    "GameState":"app/classes/states/GameState",
    "GrassTile":"app/classes/tiles/GrassTile",
    "Handler":"app/classes/Handler",
    "ImageLoader":"app/classes/gfx/ImageLoader",
    "KeyManager":"app/classes/input/KeyManager",
    "Launcher":"app/classes/launcher",
    "Player":"app/classes/entities/creatures/Player",
    "Rectangle":"app/classes/gfx/shapes/Rectangle",
    "SpriteSheet":"app/classes/gfx/SpriteSheet",
    "State":"app/classes/states/State",
    "StoneTile":"app/classes/tiles/StoneTile",
    "Tile":"app/classes/tiles/Tile",
    "TileLoader":"app/classes/tiles/TileLoader",
    "Utils":"app/classes/utils/Utils",
    "WaterTile":"app/classes/tiles/WaterTile",
    "World":"app/classes/worlds/world"
  }
});

require(['app/main']);
